name: 'vane_shelf_static_demo'
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  vane: '^0.8.2'
  shelf: '^0.6.7+2'
  shelf_static: '^0.2.4'
  args: '^0.13.7'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter

